### ISSUE TITLE
同时并发接口 会500 

### ISSUE THREAD

**Issue by zoooozz** [8treenet/gcache#10]
单个接口调用mysql 并且接入了缓存 没有什么问题 但是同时并非请求 这边直接500了

**Comment by 8treenet** [comment]
500? http的接口的500吗？？您的意思是panic了吗？ 被recover了吗？？
如果是panic，能否发个错误信息？

**Comment by zoooozz** [comment]
是recover了  
同时并发请求多个接口 就会这样 单个去请求并不会出现这样的错误 



{"time":"2020-05-30T12:23:27.105494+08:00","level":"-","prefix":"echo","file":"recover.go","line":"73","message":"[PANIC RECOVER] reflect.Set: value of type model.WalletOrder is not assignable to type model.WalletLog goroutine 146 [running]:\ngithub.com/labstack/echo/v4/middleware.RecoverWithConfig.func1.1.1(0x19a5878, 0x1000, 0x0, 0x1ab8500, 0xc000148aa0)\n\t/usr/local/var/www/go/pkg/mod/github.com/labstack/echo/v4@v4.1.16/middleware/recover.go:71 +0xee\npanic(0x183a900, 0xc0004e6000)\n\t/usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/panic.go:969 +0x166\ngithub.com/jinzhu/gorm.(*Scope).callCallbacks.func1(0xc0001ebc80)\n\t/usr/local/var/www/go/pkg/mod/github.com/jinzhu/gorm@v1.9.12/scope.go:865 +0xb0\npanic(0x183a900, 0xc0004e6000)\n\t/usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/panic.go:969 +0x166\nreflect.Value.assignTo(0x1935800, 0xc000398640, 0x99, 0x1974209, 0xb, 0x19393c0, 0x0, 0xc000639f40, 0xc0004d2000, 0x18)\n\t/usr/local/Cellar/go/1.14.2_1/libexec/src/reflect/value.go:2403 +0x426\nreflect.Value.Set(0x19393c0, 0xc0002d2700, 0x199, 0x1935800, 0xc000398640, 0x99)\n\t/usr/local/Cellar/go/1.14.2_1/libexec/src/reflect/value.go:1532 +0xbd\nreflect.Append(0x182dca0, 0xc000639f40, 0x197, 0xc000544f48, 0x1, 0x1, 0x97, 0xc0005a6908, 0x0)\n\t/usr/local/Cellar/go/1.14.2_1/libexec/src/reflect/value.go:2028 +0xe8\ngithub.com/8treenet/gcache/internal.(*callQuery).setIndirectValue(0xc00039c9a0, 0xc0001ddd00, 0xc0000c2f00, 0xa, 0x10)\n\t/usr/local/var/www/go/pkg/mod/github.com/8treenet/gcache@v1.1.4/internal/call_query.go:172 +0x17a\ngithub.com/8treenet/gcache/internal.(*callQuery).invoke(0xc00039c9a0, 0xc0001ebc80)\n\t/usr/local/var/www/go/pkg/mod/github.com/8treenet/gcache@v1.1.4/internal/call_query.go:63 +0x204\ngithub.com/jinzhu/gorm.(*Scope).callCallbacks(0xc0001ebc80, 0xc00039d420, 0x4, 0x4, 0x0)\n\t/usr/local/var/www/go/pkg/mod/github.com/jinzhu/gorm@v1.9.12/scope.go:869 +0x83\ngithub.com/jinzhu/gorm.(*DB).Find(0xc00030bad0, 0x18113a0, 0xc000639f40, 0x0, 0x0, 0x0, 0xc00030bad0)\n\t/usr/local/var/www/go/pkg/mod/github.com/jinzhu/gorm@v1.9.12/main.go:354 +0x98\npikachu/dao.(*Dao).WalletLogGetListPages(0xc0002c3e20, 0xc0004625a0, 0x0, 0xa, 0x196ff65, 0x7, 0x1, 0x1ff0040, 0xc000580480, 0xc0005451f0)\n\t/usr/local/var/www/pikachu/dao/wallet_log.go:57 +0x286\npikachu/app/wallet/log.WalletLogListPages(0xc0004625a0, 0x0, 0xa, 0xb, 0xc000545530, 0xa, 0xc0003f2680, 0x1839e80, 0xc00047c5c0)\n\t/usr/local/var/www/pikachu/app/wallet/log/func.go:15 +0x81\npikachu/app/wallet/log.AdminConsumptionLog(0x1ab8500, 0xc000148aa0, 0x5, 0x183a900)\n\t/usr/local/var/www/pikachu/app/wallet/log/http_admin.go:28 +0x87c\npikachu/open.LoginAdminMidd.func1(0x1ab8500, 0xc000148aa0, 0x10, 0x18422a0)\n\t/usr/local/var/www/pikachu/open/admin_login_midd.go:26 +0x588\ngithub.com/labstack/echo/v4.(*Echo).add.func1(0x1ab8500, 0xc000148aa0, 0x1983bcf, 0x1c)\n\t/usr/local/var/www/go/pkg/mod/github.com/labstack/echo/v4@v4.1.16/echo.go:512 +0x8a\npikachu/open.Middleware.func1.1(0x1ab8500, 0xc000148aa0, 0xc00047c530, 0xc)\n\t/usr/local/var/www/pikachu/open/midd.go:57 +0x66c\ngithub.com/labstack/echo/v4/middleware.RequestIDWithConfig.func1.1(0x1ab8500, 0xc000148aa0, 0x1014b00, 0xc000407838)\n\t/usr/local/var/www/go/pkg/mod/github.com/labstack/echo/v4@v4.1.16/middleware/request_id.go:57 +0x1f0\ngithub.com/labstack/echo/v4/middleware.RecoverWithConfig.func1.1(0x1ab8500, 0xc000148aa0, 0x0, 0x0)\n\t/usr/local/var/www/go/pkg/mod/github.com/labstack/echo/v4@v4.1.16/middleware/recover.go:78 +0x12a\ngithub.com/labstack/echo/v4/middleware.SecureWithConfig.func1.1(0x1ab8500, 0xc000148aa0, 0x2005860, 0x203001)\n\t/usr/local/var/www/go/pkg/mod/github.com/labstack/echo/v4@v4.1.16/middleware/secure.go:142 +0x4ae\ngithub.com/labstack/echo/v4/middleware.LoggerWithConfig.func2.1(0x1ab8500, 0xc000148aa0, 0x0, 0x0)\n\t/usr/local/var/www/go/pkg/mod/github.com/labstack/echo/v4@v4.1.16/middleware/logger.go:117 +0x130\ngithub.com/labstack/echo/v4/middleware.BodyLimitWithConfig.func1.1(0x1ab8500, 0xc000148aa0, 0x0, 0x0)\n\t/usr/local/var/www/go/pkg/mod/github.com/labstack/echo/v4@v4.1.16/middleware/body_limit.go:87 +0x17e\ngithub.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc00000c1e0, 0x1aa22a0, 0xc000364540, 0xc0000fc900)\n\t/usr/local/var/www/go/pkg/mod/github.com/labstack/echo/v4@v4.1.16/echo.go:623 +0x16c\nnet/http.serverHandler.ServeHTTP(0xc000364000, 0x1aa22a\n"}

**Comment by 8treenet** [comment]
1。你的模型因该是[]*OBject吧。  改成[]Object试下。
2。关了gcache试下，不要 gcache.AttachDB就行。 在跑个并发。看看是我报的还是gorm报的

**Comment by 8treenet** [comment]
。

**Comment by Y2Kai** [comment]
请问这个问题是如何解决的，是否是gcache的问题

**Comment by 8treenet** [comment]
不是




八叉树
***@***.***




------------------ 原始邮件 ------------------
发件人: Y2Kai ***@***.***&gt;
发送时间: 2021年5月18日 10:48
收件人: 8treenet/gcache ***@***.***&gt;
抄送: 8treenet ***@***.***&gt;, State change ***@***.***&gt;
主题: 回复：[8treenet/gcache] 同时并发接口 会500  (#10)





 
请问这个问题是如何解决的，是否是gcache的问题
