### ISSUE TITLE
是否可以增加对xormplus或xorm的支持，项目中用到了这个orm库，希望能够支持，谢谢。

### ISSUE THREAD

**Issue by CHCP** [8treenet/gcache#13]
RT。可以做成不依赖于某个具体的ORM。

**Comment by 8treenet** [comment]
暂时不打算更新和支持了，orm全称是对象关系映射。没有泛型那么这个对象映射真的很凑合。等go出泛型。gorm和xorm重写了。我在支持。这应该是重写

**Comment by CHCP** [comment]
OK，了解了。
