### ISSUE TITLE
Preload 不能正常地去存储层获取数据

### ISSUE THREAD

**Issue by sutra** [8treenet/gcache#16]
如下代码，` TestPreloadSkipCache`能通过， `TestPreload`会失败：

```
type TestRole struct {
	gorm.Model
	Name string
}

type TestUser struct {
	gorm.Model
	UserName string `gorm:"size:32"`
	Password string `gorm:"size:32"`
	Age      int
	Status   int
	Roles    []TestRole `gorm:"many2many:test_user_roles;"`
}

func init() {
	var e error
	addr := "user=lab password=lab dbname=lab port=5432 sslmode=disable"
	db, e = gorm.Open("postgres", addr)
	if e != nil {
		panic(e)
	}
	db.AutoMigrate(&TestRole{})
	db.AutoMigrate(&TestUser{})
	db.AutoMigrate(&TestEmail{})

	opt := gcache.DefaultOption{}
	opt.Expires = 300              //缓存时间，默认60秒。范围 30-900
	opt.Level = gcache.LevelSearch //缓存级别，默认LevelSearch。LevelDisable:关闭缓存，LevelModel:模型缓存， LevelSearch:查询缓存
	opt.AsyncWrite = false         //异步缓存更新, 默认false。 insert update delete 成功后是否异步更新缓存
	opt.PenetrationSafe = false    //开启防穿透, 默认false。

	//缓存中间件 注入到Gorm
	cachePlugin = gcache.AttachDB(db, &opt, &gcache.RedisOption{Addr: "localhost:6379"})

	InitData()
	//开启Debug，查看日志
	db.LogMode(true)
	cachePlugin.Debug()
}

func InitData() {
	cachePlugin.FlushDB()
	db.Exec("truncate test_user_roles")
	db.Exec("truncate test_roles")
	db.Exec("truncate test_users")
	db.Exec("truncate test_emails")

	roleAdmin := &TestRole{
		Name: "ADMIN",
	}
	db.Save(roleAdmin)

	roleUser := &TestRole{
		Name: "USER",
	}
	db.Save(roleUser)

	for index := 1; index < 21; index++ {
		user := &TestUser{}
		user.UserName = fmt.Sprintf("%s_%d", "name", index)
		user.Password = fmt.Sprintf("%s_%d", "password", index)
		user.Age = 20 + index
		user.Status = rand.Intn(3)
		user.Roles = []TestRole{*roleUser, *roleAdmin}
		db.Save(user)

		email := &TestEmail{}
		email.TypeID = index
		email.TestUserID = index
		db.Save(email)
	}
}

func TestPreloadSkipCache(t *testing.T) {
	var tc TestUser
	db.First(&tc, "user_name = ?", "name_1")
	assert.Equal(t, "name_1", tc.UserName)
	assert.Equal(t, 0, len(tc.Roles))

	cachePlugin.SkipCache().Preload("Roles").Find(&tc)
	assert.Equal(t, 2, len(tc.Roles))
}

func TestPreload(t *testing.T) {
	var tc TestUser
	db.First(&tc, "user_name = ?", "name_1")
	assert.Equal(t, "name_1", tc.UserName)
	assert.Equal(t, 0, len(tc.Roles))

	db.Preload("Roles").Find(&tc)
	assert.Equal(t, 2, len(tc.Roles)) // FAIL
}
```

**Comment by 8treenet** [comment]
关了gcache试下 别attach。确定下问题



杨树&nbsp;Shu&nbsp;Yang
Tel:&nbsp;+8613513517944
Twitter:&nbsp;_CharlieYang
Website:&nbsp;http://www.8tree.net


------------------ 原始邮件 ------------------
发件人: Sutra Zhou <notifications@github.com&gt;
发送时间: 2020年9月21日 12:32
收件人: 8treenet/gcache <gcache@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[8treenet/gcache] Preload 不能正常地去存储层获取数据 (#16)





 
如下代码， TestPreloadSkipCache能通过， TestPreload会失败：
 type TestRole struct { gorm.Model Name string } type TestUser struct { gorm.Model UserName string `gorm:"size:32"` Password string `gorm:"size:32"` Age      int Status   int Roles    []TestRole `gorm:"many2many:test_user_roles;"` } func init() { var e error addr := "user=lab password=lab dbname=lab port=5432 sslmode=disable" db, e = gorm.Open("postgres", addr) if e != nil { panic(e) } db.AutoMigrate(&amp;TestRole{}) db.AutoMigrate(&amp;TestUser{}) db.AutoMigrate(&amp;TestEmail{}) opt := gcache.DefaultOption{} opt.Expires = 300              //缓存时间，默认60秒。范围 30-900 opt.Level = gcache.LevelSearch //缓存级别，默认LevelSearch。LevelDisable:关闭缓存，LevelModel:模型缓存， LevelSearch:查询缓存 opt.AsyncWrite = false         //异步缓存更新, 默认false。 insert update delete 成功后是否异步更新缓存 opt.PenetrationSafe = false    //开启防穿透, 默认false。 //缓存中间件 注入到Gorm cachePlugin = gcache.AttachDB(db, &amp;opt, &amp;gcache.RedisOption{Addr: "localhost:6379"}) InitData() //开启Debug，查看日志 db.LogMode(true) cachePlugin.Debug() } func InitData() { cachePlugin.FlushDB() db.Exec("truncate test_user_roles") db.Exec("truncate test_roles") db.Exec("truncate test_users") db.Exec("truncate test_emails") roleAdmin := &amp;TestRole{ Name: "ADMIN", } db.Save(roleAdmin) roleUser := &amp;TestRole{ Name: "USER", } db.Save(roleUser) for index := 1; index < 21; index++ { user := &amp;TestUser{} user.UserName = fmt.Sprintf("%s_%d", "name", index) user.Password = fmt.Sprintf("%s_%d", "password", index) user.Age = 20 + index user.Status = rand.Intn(3) user.Roles = []TestRole{*roleUser, *roleAdmin} db.Save(user) email := &amp;TestEmail{} email.TypeID = index email.TestUserID = index db.Save(email) } } func TestPreloadSkipCache(t *testing.T) { var tc TestUser db.First(&amp;tc, "user_name = ?", "name_1") assert.Equal(t, "name_1", tc.UserName) assert.Equal(t, 0, len(tc.Roles)) cachePlugin.SkipCache().Preload("Roles").Find(&amp;tc) assert.Equal(t, 2, len(tc.Roles)) } func TestPreload(t *testing.T) { var tc TestUser db.First(&amp;tc, "user_name = ?", "name_1") assert.Equal(t, "name_1", tc.UserName) assert.Equal(t, 0, len(tc.Roles)) db.Preload("Roles").Find(&amp;tc) assert.Equal(t, 2, len(tc.Roles)) // FAIL }

**Comment by sutra** [comment]
试过了。关掉 gcache（也就是注释掉 cachePlugin = gcache.AttachDB(db, &opt, &gcache.RedisOption{Addr: "localhost:6379"})，并注视掉对 cachePlugin 引用的代码行），`TestPreload` 是能通过的。

**Comment by 8treenet** [comment]
Preload的缓存关系太复杂了。不支持。如果要用就SkipCache 跳过处理吧。
因为旁路缓存模型，不仅仅要做缓存的映射，还需要做到数据变更时缓存的失效，来保证一致。

**Comment by 8treenet** [comment]
现在的问题在于Preload，因该自动跳过。不因该出问题。只是处理缓存。
我看下这块。

**Comment by 8treenet** [comment]
现在的问题在于Preload，因该自动跳过。不因该出问题。只是不处理缓存。
我看下这块。

**Comment by sutra** [comment]
> 现在的问题在于Preload，因该自动跳过。不因该出问题。只是不处理缓存。
> 我看下这块。

好。可以看这个分支的测试代码： https://github.com/8treenet/gcache/compare/master...sutra:issue-16-preload?expand=1

**Comment by 8treenet** [comment]
修复了，v1.1.9

**Comment by 8treenet** [comment]
好了吗

**Comment by sutra** [comment]
> 好了吗

好了，谢谢。

**Comment by 8treenet** [comment]
修复了v1.1.10
