### ISSUE TITLE
Delete got panic: reflect.Value.Addr of unaddressable value

### ISSUE THREAD

**Issue by sutra** [8treenet/gcache#17]
测试代码如下：
```
func TestAssociation(t *testing.T) {
	var tc TestUser
	db.First(&tc, "user_name = ?", "name_1")
	assert.Equal(t, "name_1", tc.UserName)
	assert.Equal(t, 0, len(tc.Roles))

	cachePlugin.SkipCache().Preload("Roles").Find(&tc)
	assert.Equal(t, 2, len(tc.Roles))

	db.Preload("Roles").Find(&tc)
	assert.Equal(t, 2, len(tc.Roles))

	var adminRole TestRole
	db.Model(&adminRole).Where("name = ?", "ADMIN").First(&adminRole)
	assert.Equal(t, "ADMIN", adminRole.Name)

	db.Model(tc).Association("Roles").Delete(adminRole) // panic: reflect.Value.Addr of unaddressable value
}
```

这个删除操作会导致 `panic: reflect.Value.Addr of unaddressable value`，测试了去掉 gcache 是能通过测试的。

Other code see  #16, full code see https://github.com/8treenet/gcache/compare/master...sutra:testAssociation?expand=1

**Comment by 8treenet** [comment]
不支持Association，先skip下。等我处理下Association跳过

杨树&nbsp;Shu&nbsp;Yang
Tel:&nbsp;+8613513517944
Twitter:&nbsp;_CharlieYang
Website:&nbsp;http://www.8tree.net


------------------ Original ------------------

**Comment by sutra** [comment]
那能否有一种机制，默认不开启 gcache，只在需要时开启它呢？

**Comment by 8treenet** [comment]
你说的这个需求可以加。不难。明天我一起处理下。
常用的没有问题。外键的这几个用的很少。所以我也没覆盖到

**Comment by 8treenet** [comment]
修复了v1.1.10
