### ISSUE TITLE
请问有api文档吗？

### ISSUE THREAD

**Issue by AlwaysBusyLzc** [8treenet/gcache#5]
CreateRelative() 这个函数是不是只有关联查询的时候才需要用到，具体使用逻辑是什么?
tag 的作用是什么？

**Comment by 8treenet** [comment]
CreateRelative 用于join这种联表的查询缓存。
比如查询命令是 A连接B表的sql语句， 当B表的某字段被修改。 就可以使这条查询命令的缓存失效。
没有文档，中间件方式，比较简洁，侵入较小，可以参考example_test.go

**Comment by AlwaysBusyLzc** [comment]
刚才初步用了一下，感觉非常棒， gorm挂上这个， 写api完全不用管缓存层逻辑了， 请问这个在你们生产环境中使用了吗？

**Comment by 8treenet** [comment]
生产已在用，而且已经有别的公司再用了，不方便透漏名字。
example_test.go。打开缓存日志，打开gorm日志。基本可以做验证的，原理也简单。
思路基本也都是源自hibernate。 没有缓存的orm，会很尴尬。
有什么建议可以发我。谢谢

**Comment by AlwaysBusyLzc** [comment]
好的  感谢耐心解答。 赞一个！
