### ISSUE TITLE
gorm 这种用法都会报错，应该怎么改？

### ISSUE THREAD

**Issue by AlwaysBusyLzc** [8treenet/gcache#6]
result := dao.db.Where(&Item{RoleID: roleID}).Find(&items)
报错信息：“reflect: call of reflect.Value.FieldByName on ptr Value”

**Comment by 8treenet** [comment]
你注释了中间件的插入，试一下。如果gorm都报错，我也没招，我写的是它的中间件。
//gcache.AttachDB

**Comment by AlwaysBusyLzc** [comment]
注释掉中间件插入之后  就没问题了， 出问题的好像是这块代码：
![image](https://user-images.githubusercontent.com/19533371/76413531-91e0d600-63d0-11ea-8948-6dbaab774f2c.png)

**Comment by 8treenet** [comment]
加微信 我看不出来 4932004

**Comment by AlwaysBusyLzc** [comment]
已经搞定  老哥效率很高啊！
