### ISSUE TITLE
是否可以添加preload关联缓存?

### ISSUE THREAD

**Issue by upday7** [8treenet/gcache#7]
如题。首先非常感谢作者开发了这个牛逼的库哈哈。😁

我这里会经常用到关联的方法 related 和 association， 但是今天发现这种事不会缓存的，特别是使用preload的时候。

不知道是不是我的用法有问题或者是本身就不支持缓存？

**Comment by 8treenet** [comment]
related是支持的，请看example_test.go 里的TestQueryRelated
association和preload不支持，这2个方法直接使用的字符串，靠外键去做映射的。没有模型映射，我hook不到的。

**Comment by upday7** [comment]
了解，得到了确认放心了，谢谢了。开心🥳
