### ISSUE TITLE
请问如何将全表数据，一次set到redis缓存中

### ISSUE THREAD

**Issue by zanshichun** [8treenet/gcache#9]
在执行
golang: querys:=db.Table("dsp_campaign_frequercy").Find(&dCF).Scan(&dCF)

sql : select *from dsp_campaign_frequercy;
发现，并没有将查询出来的数据，插入到redis中，请问如何将全表数据，一次插入到redis中。

**Comment by 8treenet** [comment]
不支持全表缓存。是需要条件缓存。这个涉及到旁路的更新。。
比如某条件列查询，存入缓存，当某个模型的列被更新了，要删除缓存的。
如果要全表缓存的话，任意数据修改都全部删除，缓存已经没任何意义了

**Comment by zanshichun** [comment]
> 不支持全表缓存。是需要条件缓存。这个涉及到旁路的更新。。
> 比如某条件列查询，存入缓存，当某个模型的列被更新了，要删除缓存的。
> 如果要全表缓存的话，任意数据修改都全部删除，缓存已经没任何意义了

你好，我能加你的联系方式吗？我这边有一条数据，一直没法set到缓存中。
        dspCampaignFrequercy:=new(dbmodel.DspCampaignFrequercy)
	db:=this.db
	db.Table("dsp_campaign_frequercy").Find(&dspCampaignFrequercy,"campaign_id=?",id)
其他的表都是正常的，唯独这条，没法set进去

**Comment by 8treenet** [comment]
4932004

**Comment by 8treenet** [comment]
微信或qq都行

**Comment by zanshichun** [comment]
> 微信或qq都行

已经加了，请同意一下，谢谢
